lane :launchTest do

  UI.success "Bravo !"

  scan(
    project: "DKDetailsParallax.xcodeproj",
    code_coverage: true
  )
  xcov

end

lane :deploy do

  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "Darkkrye/DKDetailsParallax",
      name: version,
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: changelog_from_git_commits(),
      commitish: "master"
    )
  end

end
